remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Product Portfolio
description: Transforming complex business needs into platform-first, high-leverage solutions
